# Generated by Django 3.1.5 on 2021-02-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
